# Generated by Django 2.1.7 on 2019-10-27 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_tutorial_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorInfo',
        ),
    ]
